"""Recreating missing migration

Revision ID: ba513776c13f
Revises: a64cf04cf615
Create Date: 2025-03-18 10:42:04.129636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba513776c13f'
down_revision = 'a64cf04cf615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expert_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.String(length=10), nullable=False, server_default='default_value'))
        batch_op.add_column(sa.Column('status', sa.Enum('AVAILABLE', 'UNAVAILABLE', name='availabilitystatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expert_availability', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###
